apiVersion: v1
kind: Service
metadata:
  name: nginx-fe
spec:
  selector:
    app: nginx-fe
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-fe
  labels:
    app: nginx-fe
spec:
  replicas: 3
  selector:
    matchLabel:
      app: nginx-fe
  strategy:
    rollingUpdate:
      maxSurge: 33%
      maxUnavailable: 33%
  template:
    metadata:
      labels:
        app: nginx-fe
    spec:
      containers:
      - name: nginx-fe
        image: nginx:alpine
        ports:
        - containerPort: 5000  
